<!DOCTYPE html>
<html>
<head>
    <title>Manage Schedule</title>
    <meta charset='utf-8' />

</head>
<body>

<div class="wrapper">
    <div class="container" style="text-align: center;">
        <h1>Welcome</h1>
        <?php echo $this->errMsg; ?>

        <form class="form" action="auth" method="post">
            <input type="text" name="name">
            <input type="password" name="pass">
            <button type="submit">Login</button>
        </form>
    </div>

</div>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


<script type="text/javascript">
</script>

</body>